### ISSUE TITLE
The Path various features checklist

### ISSUE THREAD

**Issue by elidupree** [elidupree/eliduprees-web-games#3]
- [x] Monster graphics and behavior
- [x] Chest graphics and behavior
- [x] Input method (including visible arrow)
- [x] Main menu (including at least title, content warnings, start playing, patreon appeal, return to elidupree.com)
- [x] Way to access pause menu?
- [x] UI infrastructure (nicer behavior regarding resizing, possible full-screen, possible 90° rotation)
- [x] Optimize the sky
- [x] Consider using a trick to reduce the distortion of the companion's legs
- [x] Meta-stuff (blurb and blurb image, noscript stuff)
- [x] Consider making the hitboxes a bit smaller
- [x] Test on mobile
- [x] Consider making trees more common so you run into them more
- [x] Make there be a 10 minute timer for the whole game? With and ending screen with a message?
