### ISSUE TITLE
WebFXR various features checklist

### ISSUE THREAD

**Issue by elidupree** [elidupree/eliduprees-web-games#4]
Big UI features
- [x] Mutations
- [ ] Presets
- [x] Export to wav
- [x] Save/load using JSON
- [ ] Offline web app support
- [ ] "Share" links that embed the JSON in the URL, or something like that
- [ ] Bfxr-like box of different sounds you're editing, with duplicate button and maybe "recently undone" box

Simple UI features
- [x] Play button
- [x] Draw playback position
- [x] draw the main, final sound more prominently
- [x] Click on rendered sounds [including the intermediate ones] to play them
- [x] Loop
- [x] Undo/redo
- [x] Keyboard shortcuts for undo/redo
- [x] compute intermediate renderings and display visual representations of them
- [ ] ...and display warning when one of the effects silences most of the sound
- [x] Draw a visual indication of clipping
- [ ] Draw a warning when there is clipping in the final samples
- [x] draw the waveform
- [x] explicit toggle for some DSP effects
- [ ] Disable animations toggle
- [x] Show/hide toggle for effects on each signal
- [ ] Reimplement playback scanline

UI refinements
- [x] Draw signals out to their last effect, even if it's beyond the envelope
- [ ] Make the canvases easier to recognize/understand
- [x] Draw waveform toggles as labeled buttons instead of radio buttons with separate labels
- [x] Visually disable controls that don't currently have an effect (like disabled signals)
- [x] Make the harmonics slider hit the integers
- [ ] consider customizing the default number of significant figures per-signal
- [x] For logarithmic inputs, have approximate_from_rendered use a variable precision so it can represent a wider range
- [x] Allow scroll wheel input to go beyond the ends of the slider
- [x] Don't hijack scroll wheel input if you just used it to actually scroll (possibly: if you haven't moved the mouse since last time you scrolled using the wheel)
- [x] Tweak the size of scroll wheel increments (right now they're bigger than I like, and probably they should be based on the scroll amount)
- [ ] Give everything explicit CSS instead of using browser defaults
- [ ] Individual randomize buttons for each signal
- [ ] Lock buttons
- [x] Consider biasing random frequency ratios towards low odd limit
- [x] Make scroll wheel speed behave consistently in Chrome vs Firefox

Synth stuff
- [x] Generalized square duty
- [x] flanger
- [x] harmonics
- [x] clipping behavior (hard versus soft)
- [x] bitcrush resolution reduction
- [x] super sampling
- [x] choose output sample rate
- [x] Automatically smooth jumps/square oscillations in signals that can cause clicks (volume, flanger…)
- [x] Chorus effect
- [x] Consider a toggle to make the bitcrush frequency use an average instead of arbitrary sampling
- [x] Waveform: pink noise
- [x] Waveform: brown noise
- [x] bias the randomization so that noise isn't more likely just because there are more types of noise
- [x] Probably modify the current flanger effect because it's too easy for it not to make a big difference
- [ ] Improve bitcrush resolution UI, maybe remove it, and definitely remove it from randomization, because it too often does nothing or silences the sound
- [x] Make more consistent volumes for random sounds

Technical stuff
- [x] DOM diff
- [x] Fix filter cutoff
- [x] Fix possible NaN from slides with 0 duration
- [ ] Choose the canvas sizes relative to the input sizes/ em size at least
- [x] Fix redraws losing UI state of inputs after the first canvas (problem happens because the canvas gets replaced, messing with the siblings after it – probably fix by putting the canvases in wrapper divs)
- [x] Try to make the randomness deterministic across platforms

Meta stuff
- [ ] Finalize intro (patreon/etc)
- [x] Details for audio nerds
